name: Floor_Is_Lava
version: '${project.version}'
main: floorIsLava.FloorIsLava
api-version: '1.20'
authors: [ BlueNova ]
description: You and your friends are trapped in a world where lava will rise till only one survives! Who will it be?
depend:
  - WorldEdit
  - Multiverse-Core