name: Floor_Is_Lava
version: '${project.version}'
main: floorIsLava.FloorIsLava
api-version: '1.20'
authors: [ BlueNova ]
description: You and your friends are trapped in a world where lava will rise till only one survives! Who will it be?
depend:
  - WorldEdit
  - Multiverse-Core
commands:

  fillobby:
    description: Create a lobby to invite players.
    usage: /<command> <playerName>
    permission: floorislava.startgame

  filinvite:
    description: Invite a player to your lobby
    usage: /<command> <playerName>
    permission: floorislava.startgame

  fillist:
    description: List all pending invites and players in your lobby
    usage: /<command> <playerName>
    permission: floorislava.startgame

  filaccept:
    description: Accept an invite to a lobby
    usage: /<command> <playerName>
    permission: floorislava.play

  filleave:
    description: Leave a lobby
    usage: /<command> <playerName>
    permission: floorislava.play

  filremove:
    description: Remove a player from your lobby
    usage: /<command> <playerName>
    permission: floorislava.startgame

  filstart:
    description: Start a game when your lobby has two or more players
    usage: /<command> <playerName>
    permission: floorislava.startgame