##################################################################
###                                                            ###
###   FFFFFFFF  ll        oooo        oooo      rr   rrrrrr    ###
###   FF        ll      oo   oo     oo   oo     rr  rrr   rr   ###
###   FFFFFF    ll      oo   oo     oo   oo     rr rr          ###
###   FF        ll      oo   oo     oo   oo     rrrr           ###
###   FF        ll        ooo         ooo       rrr            ###
###                                                            ###
########################    iiii    ssssss    ####################
########################    iiii   ss    ss   ####################
########################           ss         ####################
########################    iiii    ssssss    ####################
########################    iiii         ss   ####################
########################    iiii   ss    ss   ####################
########################    iiii    ssssss    ####################
###                                                            ###
###   LL             AAAAA       VV       VV       AAAAA       ###
###   LL            AA  AA        VV     VV       AA  AA       ###
###   LL           AAAAAAA         VV   VV       AAAAAAA       ###
###   LL          AA    AA          VV VV       AA    AA       ###
###   LLLLLLL    AA     AA           VVV       AA     AA       ###
###                                                            ###
##################################################################

# How far apart each game plot should be from its neighbor (in blocks).
PlotMargin: 1000

# How big each plot will be. 50 blocks will have a 50x50 plot of land per game.
# lowering this number will lower the amount of time is needed before each start of a game.
PlotSize: 50

# How many plots (or lobbies) are there at a time.
# THIS IS THE AMOUNT OF PLOTS **ACROSS** (meaning if this is 5, that means 5x5 = 25 total plots)
# Lowering this helps very weak servers stay alive lmao (but only when lobbies are at MAX CAPACITY).
PlotAmount: 5

# This tells how long this plugin is allowed to process each tick. This is a workload distro.
# Lowering this number will increase the amount of time is needed to generate a game.
#
# Lower this number if your server begins to lag when making a new game.
# Increase this number if server does not lag but waiting time is too long for a game to start.
# MAX VALUE IS 1000
MAX_MILLIS_PER_TICK: 10