#-----------------------------------------#
#          FloorIsLava Messages           #
#-----------------------------------------#
# Uses MiniMessage format for colors, formatting, hover/click events.
# Learn more: https://docs.adventure.kyori.net/minimessage/format.html
# Placeholders are generally defined like <placeholder_name>

general:
  prefix: "<white>[<red>F</red><yellow>I</yellow><gold>L</gold><white>] </white>"
  plugin_name_formatted: "<red>Floor <yellow>Is <gold>Lava</gold></yellow></red>"
  no_permission: "<red>You don't have permission to do this!</red>"
  player_not_found: "<red>Player <aqua><player></aqua> not found (offline or misspelled?).</red>"
  already_in_game_error: "<red>You cannot do that while in a game!</red>"
  not_a_player: "<red>You must be a player to do that!</red>"
  # --- Added General Keys ---
  base_usage: "<red>Usage: /fil <group> <subcommand> [args...]</red>"
  unknown_command_group: "<red>Unknown command group: <aqua><group></aqua></red>"
  group_help_header: "<yellow>Available commands for <aqua>/fil <group></aqua>:</yellow>"
  group_help_entry: " <green>/fil <group> <subcommand></green> <white>- <usage></white>"
  unknown_subcommand: "<red>Unknown subcommand '<aqua><subcommand></aqua>' for group '<aqua><group></aqua>'.</red>"

lobby:
  created: "<green>Lobby created successfully!</green>"
  already_in_lobby: "<red>You are already in a lobby!</red>"
  not_in_lobby: "<red>You are not currently in a lobby.</red>"
  not_lobby_owner: "<red>You must be the lobby owner to do that!</red>"
  invite_sent_header: "<white>Invites sent to:</white><br><player_list>" # Command appends names
  invite_failed_header: "<red>Could not invite: </red><br><player_list>" # Command appends names/reasons
  # Inside MessageConfig.yml -> lobby section
  invite_received: "<white>You have received an invite from <aqua><inviter></aqua> to play <plugin_name>! </white><accept_button>" # Placeholder for button
  invite_accept_button_text: "<green><bold>[Accept]</bold></green>" # Text for the button
  invite_accept_button_hover: "<green>Click to accept invite from <aqua><inviter></aqua></green>" # Hover text (optional)
  invite_accepted_to_owner: "<aqua><player></aqua><white> has joined your lobby!</white>"
  invite_accepted_to_player: "<green>You joined <aqua><lobby_owner></aqua>'s lobby!</green>"
  already_invited_error: "<red>Already invited or joined: <white><player></white>.</red>"
  invited_player_in_lobby_error: "<red><player></red><red> is already in a lobby!</red>"
  kicked_player_feedback: "<white>Kicked <aqua><player></aqua>.</white>"
  kicked_player_notification: "<red>You were kicked from the lobby by <aqua><lobby_owner></aqua>.</red>"
  kick_self_error: "<red>You cannot kick yourself!</red>"
  leaving_lobby_feedback: "<white>You left <aqua><lobby_owner></aqua>'s lobby.</white>"
  player_left_notification: "<aqua><player></aqua><white> has left your lobby.</white>"
  lobby_disbanded_owner: "<dark_red>Your lobby was disbanded because you left.</dark_red>"
  lobby_disbanded_notification: "<red>The lobby owned by <aqua><lobby_owner></aqua> was disbanded.</red>"
  start_lobby_too_small: "<red>You need at least 2 players in the lobby to start!</red>"
  start_no_plots_available: "<red>No arenas available. Please wait or contact an admin.</red>"
  list_header: "<gold>--- Lobby Players ---</gold>"
  list_joined_header: "<green>Joined:"
  list_invited_header: "<yellow>Invited (Pending):"
  list_entry: "<white>- <player_name></white>"
  list_entry_owner: "<white>- <player_name></white> <gold>(Owner)</gold>"
  list_empty_joined: "<gray>(Just you!)</gray>"
  list_empty_invited: "<gray>(None)</gray>"
  list_footer: "<gold>---------------------</gold>"
  # --- Added Lobby Keys ---
  target_not_owner: "<red>Player <aqua><player></aqua> does not own a lobby!</red>"
  invite_not_pending: "<red>You do not have a pending invite from <aqua><player></aqua>.</red>"
  error_generic: "<red>An internal error occurred retrieving lobby data.</red>"
  cannot_invite_self: "<red>You cannot invite yourself!</red>"
  invite_no_valid_targets: "<red>No valid players found to invite.</red>"

game:
  generating_terrain: "<aqua>Generating terrain for your game...</aqua>"
  countdown: "<yellow>Game starting in <gold><seconds></gold>...</yellow>"
  teleporting: "<aqua>Teleporting to the arena!</aqua>"
  started: "<green>The game has begun! Last one standing wins!</green>"
  lava_death: "<aqua><player></aqua> <red>was consumed by the rising lava!</red>"
  other_death: "<aqua><player></aqua> <red>died.</red>"
  became_spectator: "<gray>You were eliminated! You are now spectating.</gray>"
  player_left_game: "<aqua><player></aqua> <yellow>has left the game.</yellow>"
  self_left_game: "<red>You left the game.</red>"
  lava_warning: "<gold>Lava</gold> <red>has reached Y=<aqua><y_level></aqua>!</red>"
  win_broadcast: "<gold><player></gold> <white>is the Lava champion!</white>"
  win_title_top: "<white>YOU WON!</white>"
  win_title_bottom: "<gold>You are the Lava Master!</gold>"
  game_over: "<red>Game Over!</red>"
  teleport_back_notice: "<yellow>Teleporting back shortly...</yellow>"
  # chaos_tnt_shower: "<gold>Look out below! TNT Shower!</gold>"

command_usage:
  lobby_invite: "<red>Usage: /fil lobby invite <player1> [player2]...</red>"
  lobby_accept: "<red>Usage: /fil lobby accept <playerWhoInvitedYou></red>"
  lobby_remove: "<red>Usage: /fil lobby remove <playerToKick></red>"
  # Add others as needed