name: FloorIsLava
version: '1.0.4'
main: com.bluenova.floorislava.FloorIsLava
authors: [ BlueNova ]
description: You and your friends are trapped in a world where lava will rise till only one survives! Who will it be?
api-version: "1.13"
depend:
  - WorldEdit
  - Multiverse-Core
softdepend:
  - WorldGuard
commands:
  fil:
    description: "main command for Floor is Lava"