name: FloorIsLava
version: '1.0-SNAPSHOT'
main: com.bluenova.floorislava.FloorIsLava
api-version: '1.20'
authors: [ BlueNova, BedlessDeus ]
description: You and your friends are trapped in a world where lava will rise till only one survives! Who will it be?
depend:
  - WorldEdit
  - Multiverse-Core