name: FloorIsLava
version: '1.0.3'
main: com.bluenova.floorislava.FloorIsLava
authors: [ BlueNova ]
description: You and your friends are trapped in a world where lava will rise till only one survives! Who will it be?
depend:
  - WorldEdit
  - Multiverse-Core
commands:
  fil:
    description: "main command for Floor is Lava"